# permissions for end users to view sources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: source-viewer-role
rules:
- apiGroups:
  - x-delivery.ocm.software
  resources:
  - sources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - x-delivery.ocm.software
  resources:
  - sources/status
  verbs:
  - get
